name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem would this solve?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this affect?
      options:
        - Interviewer Agent
        - Architect Agent
        - Writer Agent
        - Editor Agent
        - Continuity Agent
        - Web UI
        - CLI
        - Settings/Config
        - Other
