"""World Health Models - data structures for world validation and health metrics.

Contains Pydantic models for:
- Entity claims and contradictions
- World health metrics and scoring
- Relationship suggestions
"""

import logging

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


# =========================================================================
# Contradiction Detection Models
# =========================================================================


class EntityClaim(BaseModel):
    """A claim/fact extracted from an entity's description or attributes.

    Used for contradiction detection to compare facts across entities.
    """

    entity_id: str = Field(description="ID of the entity this claim is about")
    entity_name: str = Field(description="Name of the entity")
    entity_type: str = Field(default="", description="Type of entity (character, location, etc.)")
    claim: str = Field(description="The factual claim being made")
    source_text: str = Field(default="", description="Original text the claim was extracted from")


class Contradiction(BaseModel):
    """A detected contradiction between two claims.

    Represents a logical inconsistency found during world validation.
    """

    claim_a: EntityClaim = Field(description="First claim in the contradiction")
    claim_b: EntityClaim = Field(description="Second claim in the contradiction")
    severity: str = Field(
        default="medium",
        description="Severity level: 'low', 'medium', 'high', or 'critical'",
    )
    explanation: str = Field(description="Explanation of why these claims contradict")
    resolution_suggestion: str = Field(
        default="", description="Suggested way to resolve the contradiction"
    )
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Confidence score of the contradiction"
    )


# =========================================================================
# Relationship Suggestion Models
# =========================================================================


class RelationshipSuggestion(BaseModel):
    """A suggested relationship for an entity.

    Generated by the relationship suggestion system based on narrative context.
    """

    source_entity_id: str = Field(description="ID of the source entity")
    source_entity_name: str = Field(description="Name of the source entity")
    target_entity_id: str = Field(description="ID of the target entity")
    target_entity_name: str = Field(description="Name of the target entity")
    relation_type: str = Field(description="Type of relationship (e.g., 'ally_of', 'rival_of')")
    description: str = Field(default="", description="Description of the relationship")
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Confidence score for this suggestion"
    )
    bidirectional: bool = Field(
        default=False, description="Whether the relationship goes both ways"
    )


# =========================================================================
# World Health Metrics Models
# =========================================================================


class WorldHealthMetrics(BaseModel):
    """Comprehensive health metrics for a story world.

    Aggregates various quality indicators including entity counts,
    orphan detection, circular relationships, and quality scores.
    """

    # Entity counts
    total_entities: int = Field(default=0, description="Total number of entities")
    entity_counts: dict[str, int] = Field(default_factory=dict, description="Entity counts by type")
    total_relationships: int = Field(default=0, description="Total number of relationships")

    # Orphan detection
    orphan_count: int = Field(default=0, description="Number of orphan entities")
    orphan_entities: list[dict] = Field(
        default_factory=list,
        description="List of orphan entities with id, name, type",
    )

    # Circular relationship detection
    circular_count: int = Field(default=0, description="Number of circular relationship chains")
    circular_relationships: list[dict] = Field(
        default_factory=list, description="Details of circular relationship chains"
    )

    # Quality metrics
    average_quality: float = Field(
        default=0.0, ge=0.0, le=10.0, description="Average quality score across entities"
    )
    quality_distribution: dict[str, int] = Field(
        default_factory=dict,
        description="Distribution of entities by quality bracket (e.g., '0-2': 5)",
    )
    low_quality_entities: list[dict] = Field(
        default_factory=list,
        description="Entities with quality below threshold",
    )

    # Contradiction detection
    contradiction_count: int = Field(default=0, description="Number of detected contradictions")
    contradictions: list[dict] = Field(
        default_factory=list, description="List of detected contradictions"
    )

    # Computed metrics
    relationship_density: float = Field(
        default=0.0,
        ge=0.0,
        description="Relationships per entity ratio",
    )
    health_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Overall world health score (0-100)",
    )

    # Recommendations
    recommendations: list[str] = Field(
        default_factory=list, description="List of recommendations to improve world health"
    )

    def calculate_health_score(self) -> float:
        """Calculate overall health score based on metrics.

        Scoring factors:
        - Base score: 100
        - Orphan penalty: -2 per orphan (max -20)
        - Circular penalty: -5 per circular chain (max -25)
        - Low quality penalty: -3 per low quality entity (max -30)
        - Contradiction penalty: -5 per contradiction (max -25)
        - Density bonus: +10 if density >= 1.5, +5 if >= 1.0

        Returns:
            Health score between 0 and 100.
        """
        score = 100.0

        # Orphan penalty
        orphan_penalty = min(self.orphan_count * 2, 20)
        score -= orphan_penalty

        # Circular relationship penalty
        circular_penalty = min(self.circular_count * 5, 25)
        score -= circular_penalty

        # Low quality entity penalty
        low_quality_penalty = min(len(self.low_quality_entities) * 3, 30)
        score -= low_quality_penalty

        # Contradiction penalty
        contradiction_penalty = min(self.contradiction_count * 5, 25)
        score -= contradiction_penalty

        # Density bonus
        if self.relationship_density >= 1.5:
            score += 10
        elif self.relationship_density >= 1.0:
            score += 5

        # Ensure score is within bounds
        self.health_score = max(0.0, min(100.0, score))
        logger.debug(
            f"Calculated health score: {self.health_score:.1f} "
            f"(orphan_penalty={orphan_penalty}, circular_penalty={circular_penalty}, "
            f"low_quality_penalty={low_quality_penalty}, contradiction_penalty={contradiction_penalty})"
        )
        return self.health_score

    def generate_recommendations(self) -> list[str]:
        """Generate recommendations based on health metrics.

        Returns:
            List of actionable recommendations.
        """
        recommendations = []

        # Orphan recommendations
        if self.orphan_count > 0:
            if self.orphan_count == 1 and self.orphan_entities:
                # Guard access to orphan_entities[0] in case list is unexpectedly empty
                orphan_name = self.orphan_entities[0].get("name", "Unknown")
                recommendations.append(
                    f"1 entity has no relationships. Consider adding connections for: {orphan_name}"
                )
            elif self.orphan_count == 1:
                # Fallback if orphan_entities is empty but count says 1
                recommendations.append(
                    "1 entity has no relationships. Consider adding connections."
                )
            else:
                recommendations.append(
                    f"{self.orphan_count} entities have no relationships. "
                    f"Use 'Suggest Relationships' to add meaningful connections."
                )

        # Circular relationship recommendations
        if self.circular_count > 0:
            recommendations.append(
                f"{self.circular_count} circular relationship chain(s) detected. "
                f"Review for unintended loops in hierarchical relationships."
            )

        # Low quality recommendations
        if len(self.low_quality_entities) > 0:
            recommendations.append(
                f"{len(self.low_quality_entities)} entities have low quality scores. "
                f"Consider refining their descriptions using 'Improve Quality'."
            )

        # Contradiction recommendations
        if self.contradiction_count > 0:
            recommendations.append(
                f"{self.contradiction_count} potential contradiction(s) detected. "
                f"Review entity descriptions for consistency."
            )

        # Density recommendations
        if self.relationship_density < 1.0 and self.total_entities > 5:
            recommendations.append(
                f"Relationship density is low ({self.relationship_density:.2f}). "
                f"Consider adding more relationships to create a richer world."
            )

        # Entity balance recommendations
        if self.entity_counts:
            char_count = self.entity_counts.get("character", 0)
            loc_count = self.entity_counts.get("location", 0)
            if char_count > 0 and loc_count == 0:
                recommendations.append(
                    "No locations defined. Add locations to ground your characters in a world."
                )
            if loc_count > 0 and char_count == 0:
                recommendations.append(
                    "No characters defined. Add characters to populate your locations."
                )

        self.recommendations = recommendations
        logger.debug(
            f"Generated {len(recommendations)} recommendations: "
            f"{recommendations if recommendations else 'none (healthy world)'}"
        )
        return recommendations
